package com.jiangdg.demo

import com.google.firebase.auth.FirebaseUser

class Global {
    var pdfUri: String? = null
    var doctorUID: String? = null
    var patientId: String? = null
    var user: FirebaseUser? = null
    var swedeScore: String? = null
    var swedeScoreResult: String? = null
    var reidScore: String? = null
    var reidScoreResult: String? = null
    var chiefComplaintList: List<String> = ArrayList()
    var colposcopyFindingsList: List<String> = ArrayList()
    var cytologyReportList: List<String> = ArrayList()
    var finalImpressionList: List<String> = ArrayList()
    var pathologicalReportList: List<String> = ArrayList()
    var precautionsList: List<String> = ArrayList()
    var treatmentList: List<String> = ArrayList()
    var imageList: List<String> = ArrayList()
    var swedeAcetoUptakeList: String? = null
    var swedeMarginsList: String? = null
    var swedeVesselsList: String? = null
    var swedeLessionSizeList: String? = null
    var swedeIodineStainingList: String? = null
    var reidMarginsList: String? = null
    var reidColorList: String? = null
    var reidVesselsList: String? = null
    var reidIodineStainingList: String? = null
    var reidVal1 = 0
    var reidVal2 = 0
    var reidVal3= 0
    var reidVal4 = 0
    var reidSum = 0
    var swedeVal1 = 0
    var swedeVal2 = 0
    var swedeVal3 = 0
    var swedeVal4= 0
    var swedeSum = 0
    var swedeVal5 = 0
    var analInjuriesorinjurytoanalfoldsList: List<String> = ArrayList()
    var erythemaList: List<String> = ArrayList()
    var greenFilterList: List<String> = ArrayList()
    var posteriorFourchetteList: List<String> = ArrayList()
    var presenceOfForeignBodiesList: List<String> = ArrayList()
    var SkinOrMucosalTraumaList: List<String> = ArrayList()
    var stainingEffectList: List<String> = ArrayList()
    var swabSampleList: List<String> = ArrayList()
    var cryoSurgeryList: List<String> = ArrayList()
    var freezingDoneList: List<String> = ArrayList()
    var iceBallList: List<String> = ArrayList()
    var probeTipList: List<String> = ArrayList()
    var thawCycleList: List<String> = ArrayList()

    var cavumUteriList: List<String> = ArrayList()
    var cervicalCanalBleedingList: List<String> = ArrayList()
    var cervicalStenosisList: List<String> = ArrayList()
    var craurosisFornicisList: List<String> = ArrayList()
    var EndometriumList: List<String> = ArrayList()
    var fibroidAdditionList: List<String> = ArrayList()
    var focalLesionsList: List<String> = ArrayList()
    var HyperplasiaList: List<String> = ArrayList()
    var intraCervicalAdditionList: List<String> = ArrayList()
    var intraUterineAdhesionList: List<String> = ArrayList()
    var isthmusUteriList: List<String> = ArrayList()
    var iUDList: List<String> = ArrayList()
    var leftTubalOstiaList: List<String> = ArrayList()
    var lesionsList: List<String> = ArrayList()
    var myomaList: List<String> = ArrayList()
    var nulliparaList: List<String> = ArrayList()
    var polypsList: List<String> = ArrayList()
    var rightTubalOstiaList: List<String> = ArrayList()
    var uterusList: List<String> = ArrayList()


    var anaesthesiaModeList: List<String> = ArrayList()
    var operationModeList: List<String> = ArrayList()
    var BisthourySpecificationList: List<String> = ArrayList()
    var operationTimeList: List<String> = ArrayList()
    var operationDeepnessList: List<String> = ArrayList()
    var daysAfterOperationList: List<String> = ArrayList()
    var operationRangeList: List<String> = ArrayList()
    var pathologyResultAfterOperationList: String? = null
    var diagnosisBeforeOperationList: String? = null
    var bleedingWhileOperationList: List<String> = ArrayList()

    companion object {
        var loginTime:String = ""
        val imageList: MutableList<String> = mutableListOf()
        var pathologyResultAfterOperationList: String=""
        var diagnosisBeforeOperationList: String=""
        val daysAfterOperationList: MutableList<String> = mutableListOf()
        val operationRangeList: MutableList<String> = mutableListOf()
        val operationDeepnessList: MutableList<String> = mutableListOf()
        val bleedingWhileOperationList: MutableList<String> = mutableListOf()
        val operationTimeList: MutableList<String> = mutableListOf()
        val bisthourySpecificationList: MutableList<String> = mutableListOf()
        val operationModeList: MutableList<String> = mutableListOf()
        val anaesthesiaModeList: MutableList<String> = mutableListOf()
        val cavumUteriList: MutableList<String> = mutableListOf()
        val cervicalCanalBleedingList: MutableList<String> = mutableListOf()
        val cervicalStenosisList: MutableList<String> = mutableListOf()
        val craurosisFornicisList: MutableList<String> = mutableListOf()
        val endometriumList: MutableList<String> = mutableListOf()
        val fibroidAdditionList: MutableList<String> = mutableListOf()
        val focalLesionsList: MutableList<String> = mutableListOf()
        val hyperplasiaList: MutableList<String> = mutableListOf()
        val intraCervicalAdditionList: MutableList<String> = mutableListOf()
        val intraUterineAdhesionList: MutableList<String> = mutableListOf()
        val isthmusUteriList: MutableList<String> = mutableListOf()
        val iUDList: MutableList<String> = mutableListOf()
        val leftTubalOstiaList: MutableList<String> = mutableListOf()
        val lesionsList: MutableList<String> = mutableListOf()
        val myomaList: MutableList<String> = mutableListOf()
        val nulliparaList: MutableList<String> = mutableListOf()
        val polypsList: MutableList<String> = mutableListOf()
        val rightTubalOstiaList: MutableList<String> = mutableListOf()
        val uterusList: MutableList<String> = mutableListOf()
        val thawCycleList: MutableList<String> = mutableListOf()
        val probeTipList: MutableList<String> = mutableListOf()
        val iceBallList: MutableList<String> = mutableListOf()
        val freezingDoneList: MutableList<String> = mutableListOf()
        val cryoSurgeryList: MutableList<String> = mutableListOf()
        val swabSampleList:  MutableList<String> = mutableListOf()
        val stainingEffectList:  MutableList<String> = mutableListOf()
        val skinOrMucosalTraumaList:  MutableList<String> = mutableListOf()
        val presenceOfForeignBodiesList:  MutableList<String> = mutableListOf()
        val posteriorFourchetteList:  MutableList<String> = mutableListOf()
        val greenFilterList:  MutableList<String> = mutableListOf()
        val erythemaList:  MutableList<String> = mutableListOf()
        val analInjuriesorinjurytoanalfoldsList:  MutableList<String> = mutableListOf()
        var reidVal4: Int = 0
        var reidVal3: Int = 0
        var reidVal2: Int = 0
        var reidVal1: Int = 0
        var reidIodineStainingList:String = ""
        var reidVesselsList: String = ""
        var reidMarginsList: String = ""
        var reidColorList: String = ""
        var reidSum: Int = 0
        var reidScoreResult: String = ""
        var reidScore:Int = 0
        var swedeVal5: Int = 0
        var swedeVal4: Int =0
        var swedeVal3: Int = 0
        var swedeVal2: Int = 0
        var swedeVal1: Int = 0
        var swedeScore: String = ""
        var swedeVesselsList: String = ""
        var swedeIodineStainingList: String = ""
        var swedeAcetoUptakeList: String = ""
        var swedeLessionSizeList: String = ""
        var swedeScoreResult: String = ""
        var swedeMarginsList: String = ""
        var swedeSum: Int = 0
        var chiefComplaintList: MutableList<String> = mutableListOf()
        var treatmentList:  MutableList<String> = mutableListOf()
        var precautionsList:  MutableList<String> = mutableListOf()
        var pathologicalReportList:  MutableList<String> = mutableListOf()
        var finalImpressionList:  MutableList<String> = mutableListOf()
        var cytologyReportList:  MutableList<String> = mutableListOf()
        var urologyFindingsList:  MutableList<String> = mutableListOf()
        var pdfUri: String = ""
        var patientId: String =""
        var doctorUID: String = ""
    }


}